### ISSUE TITLE
default argument in blogdown::new_post has changed

### ISSUE THREAD

**Issue by cderv** [rbind/apreshill#21]
Hi @apreshill 

From rstudio/blogdown#379, we discover that there was a change in `blogdown::new_post()` argument name that was of impact to new users and still documented. It is about `rmd = FALSE` that no more exist and was replace by `ext = getOption('blogdown.ext', '.md')` instead.

Maybe it is possible to update your post about that as I believe lots of new user rely on your great blog about blogdown  
* https://apreshill.rbind.io/post/up-and-running-with-blogdown/#new-markdown-posts
* https://github.com/rbind/apreshill/blob/master/content/post/2017-06-12-up-and-running-with-blogdown.Rmd

cheers

**Comment by apreshill** [comment]
thanks, see dee8a4ffc3fb7b80237a262e679160eeb8ad12b9, in response to https://github.com/rstudio/blogdown/issues/379
