### ISSUE TITLE
Search function not working

### ISSUE THREAD

**Issue by YTLogos** [rbind/apreshill#34]
Hi Alison,
Your personal website is wonderful and I followed your template to create my own website. I found that built-in search function does not work in website. So I google the issue and found this [link](https://github.com/wowchemy/wowchemy-hugo-modules/issues/987). However, it didn't solve the problem. So do you have any ideas to solve it? Thanks!

Best wishes,
Tao

**Comment by YTLogos** [comment]
OMG, sorry I just noticed one of pull requests #32  fixed the bug. Nice!

**Comment by apreshill** [comment]
Hi @YTLogos! Yes that was an early Christmas gift for sure- @R-CoderDotCom saved my site and I'm so thankful ❤️  Go forth and copy that layout file 🥰
